// flow-typed signature: 1b775b98d9f50134ffa8cd533ac60358
// flow-typed version: <<STUB>>/alex_v^6.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alex/cli' {
  declare module.exports: any;
}

declare module 'alex/filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alex/cli.js' {
  declare module.exports: $Exports<'alex/cli'>;
}
declare module 'alex/filter.js' {
  declare module.exports: $Exports<'alex/filter'>;
}
declare module 'alex/index' {
  declare module.exports: $Exports<'alex'>;
}
declare module 'alex/index.js' {
  declare module.exports: $Exports<'alex'>;
}
