// flow-typed signature: 250ad751170a812388724ca9c121e887
// flow-typed version: <<STUB>>/babel-preset-gatsby_v^0.1.5/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-gatsby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-gatsby/index' {
  declare module.exports: $Exports<'babel-preset-gatsby'>;
}
declare module 'babel-preset-gatsby/index.js' {
  declare module.exports: $Exports<'babel-preset-gatsby'>;
}
