// flow-typed signature: 42f7b2204c6d77f9f5408029a015fa66
// flow-typed version: <<STUB>>/gatsby-transformer-remark_v^2.1.19/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-transformer-remark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-transformer-remark' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-transformer-remark/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-remark/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-remark/hast-processing' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-remark/on-node-create' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-transformer-remark/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-transformer-remark/extend-node-type'>;
}
declare module 'gatsby-transformer-remark/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-remark/gatsby-node'>;
}
declare module 'gatsby-transformer-remark/hast-processing.js' {
  declare module.exports: $Exports<'gatsby-transformer-remark/hast-processing'>;
}
declare module 'gatsby-transformer-remark/index' {
  declare module.exports: $Exports<'gatsby-transformer-remark'>;
}
declare module 'gatsby-transformer-remark/index.js' {
  declare module.exports: $Exports<'gatsby-transformer-remark'>;
}
declare module 'gatsby-transformer-remark/on-node-create.js' {
  declare module.exports: $Exports<'gatsby-transformer-remark/on-node-create'>;
}
