// flow-typed signature: c7246a7810c9ad23df3bb74744e96c94
// flow-typed version: <<STUB>>/gatsby-plugin-offline_v^2.0.6/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-offline/app-shell' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-offline/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-offline/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-offline/get-resources-from-html' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-offline/sw-append' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-offline/app-shell.js' {
  declare module.exports: $Exports<'gatsby-plugin-offline/app-shell'>;
}
declare module 'gatsby-plugin-offline/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-offline/gatsby-browser'>;
}
declare module 'gatsby-plugin-offline/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-offline/gatsby-node'>;
}
declare module 'gatsby-plugin-offline/get-resources-from-html.js' {
  declare module.exports: $Exports<'gatsby-plugin-offline/get-resources-from-html'>;
}
declare module 'gatsby-plugin-offline/index' {
  declare module.exports: $Exports<'gatsby-plugin-offline'>;
}
declare module 'gatsby-plugin-offline/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-offline'>;
}
declare module 'gatsby-plugin-offline/sw-append.js' {
  declare module.exports: $Exports<'gatsby-plugin-offline/sw-append'>;
}
