// flow-typed signature: 9723263ab94dce6ac22b1b30ba4bdbbb
// flow-typed version: <<STUB>>/gatsby_v^2.0.85/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby/cache-dir/__tests__/error-overlay-handler' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/find-page' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/minimal-config' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-browser-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-browser' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-ssr' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-ssr-docs' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-runner-browser-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-runner-browser' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-runner-ssr' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-ssr-docs' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/create-react-context' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/default-html' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/develop-static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/emitter' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/ensure-resources' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/error-overlay-handler' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/find-page' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/gatsby-browser-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/json-store' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/navigation' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/parse-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/prefetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/production-app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/public-page-renderer-dev' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/public-page-renderer-prod' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/public-page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/react-lifecycles-compat' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/register-service-worker' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/root' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/socketIo' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/create-react-context' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/default-html' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/develop-static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/emitter' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/ensure-resources' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/error-overlay-handler' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/find-page' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/gatsby-browser-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/json-store' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/navigation' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/parse-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/prefetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/production-app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/public-page-renderer-dev' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/public-page-renderer-prod' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/public-page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/react-lifecycles-compat' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/register-service-worker' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/root' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/socketIo' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bin/gatsby' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/__mocks__/resolve-module-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/get-config-file' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/load' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/validate' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/log-line-function' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/page-hot-reloader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/prefer-default' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/resolve-module-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-javascript' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/data-explorer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/repl' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/serve' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/loki/custom-comparators' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/loki/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/loki/nodes-query' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/loki/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/node-tracking' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/nodes-query' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/internal-data-bridge/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/load-babel-config/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/load-babel-config/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/prod-404/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/prod-404/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/file-parser' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/graphql-errors' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/page-query-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/pages-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-compiler' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-queue' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-watcher' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/redirects-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/joi-schemas/joi' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions/add-page-dependency' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/plugin-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/api-to-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/babelrc' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/component-data-dependencies' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/components' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/flattened-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/jobs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/json-data-paths' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/last-action' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes-touched' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/pages' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/program' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/redirects' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/static-query-components' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/status' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/thirdPartySchemas' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/webpack' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/run-sift' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/build-connection-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/build-node-connections' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/build-node-types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/create-key' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/create-sort-field' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/create-type-name' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/data-tree-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer-graphql-input-fields-from-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer-graphql-input-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer-graphql-type' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/lazy-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/node-interface' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/page-dependency-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/type-conflict-reporter' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/type-date' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/type-file' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-browser-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-node-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-runner-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-loader-helpers' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-loader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-parse-to-ast' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/browserslist' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/cache' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/checkpoints-promise' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/create-content-digest' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/create-node-id' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/eslint-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-hash-fn' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-ssl-cert' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-static-dir' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/html-renderer-queue' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/is-32-bit-integer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/js-chunk-names' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/local-eslint-config-finder' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/merge-gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/prepare-regex' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/profile' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/source-nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/test-require-error' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/tracer/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/tracer/zipkin-local' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-helpers' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack.config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/websocket-manager' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/worker' {
  declare module.exports: any;
}

declare module 'gatsby/graphql' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby/cache-dir/__tests__/error-overlay-handler.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/error-overlay-handler'>;
}
declare module 'gatsby/cache-dir/__tests__/find-page.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/find-page'>;
}
declare module 'gatsby/cache-dir/__tests__/minimal-config.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/minimal-config'>;
}
declare module 'gatsby/cache-dir/__tests__/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/static-entry'>;
}
declare module 'gatsby/cache-dir/__tests__/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/strip-prefix'>;
}
declare module 'gatsby/cache-dir/api-runner-browser-plugins.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-browser-plugins'>;
}
declare module 'gatsby/cache-dir/api-runner-browser.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-browser'>;
}
declare module 'gatsby/cache-dir/api-runner-ssr.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-ssr'>;
}
declare module 'gatsby/cache-dir/api-ssr-docs.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-ssr-docs'>;
}
declare module 'gatsby/cache-dir/app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/app'>;
}
declare module 'gatsby/cache-dir/commonjs/api-runner-browser-plugins.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-runner-browser-plugins'>;
}
declare module 'gatsby/cache-dir/commonjs/api-runner-browser.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-runner-browser'>;
}
declare module 'gatsby/cache-dir/commonjs/api-runner-ssr.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-runner-ssr'>;
}
declare module 'gatsby/cache-dir/commonjs/api-ssr-docs.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-ssr-docs'>;
}
declare module 'gatsby/cache-dir/commonjs/app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/app'>;
}
declare module 'gatsby/cache-dir/commonjs/create-react-context.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/create-react-context'>;
}
declare module 'gatsby/cache-dir/commonjs/default-html.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/default-html'>;
}
declare module 'gatsby/cache-dir/commonjs/develop-static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/develop-static-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/emitter.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/emitter'>;
}
declare module 'gatsby/cache-dir/commonjs/ensure-resources.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/ensure-resources'>;
}
declare module 'gatsby/cache-dir/commonjs/error-overlay-handler.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/error-overlay-handler'>;
}
declare module 'gatsby/cache-dir/commonjs/find-page.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/find-page'>;
}
declare module 'gatsby/cache-dir/commonjs/gatsby-browser-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/gatsby-browser-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/json-store.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/json-store'>;
}
declare module 'gatsby/cache-dir/commonjs/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/loader'>;
}
declare module 'gatsby/cache-dir/commonjs/navigation.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/navigation'>;
}
declare module 'gatsby/cache-dir/commonjs/page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/page-renderer'>;
}
declare module 'gatsby/cache-dir/commonjs/parse-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/parse-path'>;
}
declare module 'gatsby/cache-dir/commonjs/prefetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/prefetch'>;
}
declare module 'gatsby/cache-dir/commonjs/production-app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/production-app'>;
}
declare module 'gatsby/cache-dir/commonjs/public-page-renderer-dev.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/public-page-renderer-dev'>;
}
declare module 'gatsby/cache-dir/commonjs/public-page-renderer-prod.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/public-page-renderer-prod'>;
}
declare module 'gatsby/cache-dir/commonjs/public-page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/public-page-renderer'>;
}
declare module 'gatsby/cache-dir/commonjs/react-lifecycles-compat.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/react-lifecycles-compat'>;
}
declare module 'gatsby/cache-dir/commonjs/register-service-worker.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/register-service-worker'>;
}
declare module 'gatsby/cache-dir/commonjs/root.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/root'>;
}
declare module 'gatsby/cache-dir/commonjs/socketIo.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/socketIo'>;
}
declare module 'gatsby/cache-dir/commonjs/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/static-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/strip-prefix'>;
}
declare module 'gatsby/cache-dir/create-react-context.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/create-react-context'>;
}
declare module 'gatsby/cache-dir/default-html.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/default-html'>;
}
declare module 'gatsby/cache-dir/develop-static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/develop-static-entry'>;
}
declare module 'gatsby/cache-dir/emitter.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/emitter'>;
}
declare module 'gatsby/cache-dir/ensure-resources.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/ensure-resources'>;
}
declare module 'gatsby/cache-dir/error-overlay-handler.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/error-overlay-handler'>;
}
declare module 'gatsby/cache-dir/find-page.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/find-page'>;
}
declare module 'gatsby/cache-dir/gatsby-browser-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/gatsby-browser-entry'>;
}
declare module 'gatsby/cache-dir/json-store.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/json-store'>;
}
declare module 'gatsby/cache-dir/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/loader'>;
}
declare module 'gatsby/cache-dir/navigation.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/navigation'>;
}
declare module 'gatsby/cache-dir/page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/page-renderer'>;
}
declare module 'gatsby/cache-dir/parse-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/parse-path'>;
}
declare module 'gatsby/cache-dir/prefetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/prefetch'>;
}
declare module 'gatsby/cache-dir/production-app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/production-app'>;
}
declare module 'gatsby/cache-dir/public-page-renderer-dev.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/public-page-renderer-dev'>;
}
declare module 'gatsby/cache-dir/public-page-renderer-prod.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/public-page-renderer-prod'>;
}
declare module 'gatsby/cache-dir/public-page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/public-page-renderer'>;
}
declare module 'gatsby/cache-dir/react-lifecycles-compat.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/react-lifecycles-compat'>;
}
declare module 'gatsby/cache-dir/register-service-worker.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/register-service-worker'>;
}
declare module 'gatsby/cache-dir/root.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/root'>;
}
declare module 'gatsby/cache-dir/socketIo.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/socketIo'>;
}
declare module 'gatsby/cache-dir/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/static-entry'>;
}
declare module 'gatsby/cache-dir/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/strip-prefix'>;
}
declare module 'gatsby/dist/bin/gatsby.js' {
  declare module.exports: $Exports<'gatsby/dist/bin/gatsby'>;
}
declare module 'gatsby/dist/bootstrap/__mocks__/resolve-module-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/__mocks__/resolve-module-exports'>;
}
declare module 'gatsby/dist/bootstrap/get-config-file.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/get-config-file'>;
}
declare module 'gatsby/dist/bootstrap/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/index'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/index'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/load.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/load'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/validate.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/validate'>;
}
declare module 'gatsby/dist/bootstrap/log-line-function.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/log-line-function'>;
}
declare module 'gatsby/dist/bootstrap/page-hot-reloader.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/page-hot-reloader'>;
}
declare module 'gatsby/dist/bootstrap/prefer-default.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/prefer-default'>;
}
declare module 'gatsby/dist/bootstrap/resolve-module-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/resolve-module-exports'>;
}
declare module 'gatsby/dist/commands/build-html.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-html'>;
}
declare module 'gatsby/dist/commands/build-javascript.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-javascript'>;
}
declare module 'gatsby/dist/commands/build.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build'>;
}
declare module 'gatsby/dist/commands/data-explorer.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/data-explorer'>;
}
declare module 'gatsby/dist/commands/develop-html.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop-html'>;
}
declare module 'gatsby/dist/commands/develop.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop'>;
}
declare module 'gatsby/dist/commands/repl.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/repl'>;
}
declare module 'gatsby/dist/commands/serve.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/serve'>;
}
declare module 'gatsby/dist/db/index.js' {
  declare module.exports: $Exports<'gatsby/dist/db/index'>;
}
declare module 'gatsby/dist/db/loki/custom-comparators.js' {
  declare module.exports: $Exports<'gatsby/dist/db/loki/custom-comparators'>;
}
declare module 'gatsby/dist/db/loki/index.js' {
  declare module.exports: $Exports<'gatsby/dist/db/loki/index'>;
}
declare module 'gatsby/dist/db/loki/nodes-query.js' {
  declare module.exports: $Exports<'gatsby/dist/db/loki/nodes-query'>;
}
declare module 'gatsby/dist/db/loki/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/db/loki/nodes'>;
}
declare module 'gatsby/dist/db/node-tracking.js' {
  declare module.exports: $Exports<'gatsby/dist/db/node-tracking'>;
}
declare module 'gatsby/dist/db/nodes-query.js' {
  declare module.exports: $Exports<'gatsby/dist/db/nodes-query'>;
}
declare module 'gatsby/dist/db/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/db/nodes'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/index'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge/index'>;
}
declare module 'gatsby/dist/internal-plugins/load-babel-config/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/load-babel-config/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/load-babel-config/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/load-babel-config/index'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404/index'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/file-parser.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/file-parser'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/graphql-errors.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/graphql-errors'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/index'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/page-query-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/page-query-runner'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/pages-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/pages-writer'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-compiler.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-compiler'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-queue.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-queue'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-runner'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-watcher.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-watcher'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/redirects-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/redirects-writer'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/utils.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/utils'>;
}
declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index'>;
}
declare module 'gatsby/dist/joi-schemas/joi.js' {
  declare module.exports: $Exports<'gatsby/dist/joi-schemas/joi'>;
}
declare module 'gatsby/dist/redux/actions.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions'>;
}
declare module 'gatsby/dist/redux/actions/add-page-dependency.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions/add-page-dependency'>;
}
declare module 'gatsby/dist/redux/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/index'>;
}
declare module 'gatsby/dist/redux/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/nodes'>;
}
declare module 'gatsby/dist/redux/plugin-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/plugin-runner'>;
}
declare module 'gatsby/dist/redux/reducers/api-to-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/api-to-plugins'>;
}
declare module 'gatsby/dist/redux/reducers/babelrc.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/babelrc'>;
}
declare module 'gatsby/dist/redux/reducers/component-data-dependencies.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/component-data-dependencies'>;
}
declare module 'gatsby/dist/redux/reducers/components.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/components'>;
}
declare module 'gatsby/dist/redux/reducers/config.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/config'>;
}
declare module 'gatsby/dist/redux/reducers/flattened-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/flattened-plugins'>;
}
declare module 'gatsby/dist/redux/reducers/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/index'>;
}
declare module 'gatsby/dist/redux/reducers/jobs.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/jobs'>;
}
declare module 'gatsby/dist/redux/reducers/json-data-paths.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/json-data-paths'>;
}
declare module 'gatsby/dist/redux/reducers/last-action.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/last-action'>;
}
declare module 'gatsby/dist/redux/reducers/nodes-touched.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes-touched'>;
}
declare module 'gatsby/dist/redux/reducers/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes'>;
}
declare module 'gatsby/dist/redux/reducers/pages.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/pages'>;
}
declare module 'gatsby/dist/redux/reducers/plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/plugins'>;
}
declare module 'gatsby/dist/redux/reducers/program.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/program'>;
}
declare module 'gatsby/dist/redux/reducers/redirects.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/redirects'>;
}
declare module 'gatsby/dist/redux/reducers/schema.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/schema'>;
}
declare module 'gatsby/dist/redux/reducers/static-query-components.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/static-query-components'>;
}
declare module 'gatsby/dist/redux/reducers/status.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/status'>;
}
declare module 'gatsby/dist/redux/reducers/thirdPartySchemas.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/thirdPartySchemas'>;
}
declare module 'gatsby/dist/redux/reducers/webpack.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/webpack'>;
}
declare module 'gatsby/dist/redux/run-sift.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/run-sift'>;
}
declare module 'gatsby/dist/schema/build-connection-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/build-connection-fields'>;
}
declare module 'gatsby/dist/schema/build-node-connections.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/build-node-connections'>;
}
declare module 'gatsby/dist/schema/build-node-types.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/build-node-types'>;
}
declare module 'gatsby/dist/schema/create-key.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/create-key'>;
}
declare module 'gatsby/dist/schema/create-sort-field.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/create-sort-field'>;
}
declare module 'gatsby/dist/schema/create-type-name.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/create-type-name'>;
}
declare module 'gatsby/dist/schema/data-tree-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/data-tree-utils'>;
}
declare module 'gatsby/dist/schema/index.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/index'>;
}
declare module 'gatsby/dist/schema/infer-graphql-input-fields-from-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer-graphql-input-fields-from-fields'>;
}
declare module 'gatsby/dist/schema/infer-graphql-input-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer-graphql-input-fields'>;
}
declare module 'gatsby/dist/schema/infer-graphql-type.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer-graphql-type'>;
}
declare module 'gatsby/dist/schema/lazy-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/lazy-fields'>;
}
declare module 'gatsby/dist/schema/node-interface.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/node-interface'>;
}
declare module 'gatsby/dist/schema/node.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/node'>;
}
declare module 'gatsby/dist/schema/page-dependency-resolver.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/page-dependency-resolver'>;
}
declare module 'gatsby/dist/schema/type-conflict-reporter.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/type-conflict-reporter'>;
}
declare module 'gatsby/dist/schema/types/type-date.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/type-date'>;
}
declare module 'gatsby/dist/schema/types/type-file.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/type-file'>;
}
declare module 'gatsby/dist/utils/api-browser-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-browser-docs'>;
}
declare module 'gatsby/dist/utils/api-node-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-node-docs'>;
}
declare module 'gatsby/dist/utils/api-runner-node.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-runner-node'>;
}
declare module 'gatsby/dist/utils/babel-loader-helpers.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-loader-helpers'>;
}
declare module 'gatsby/dist/utils/babel-loader.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-loader'>;
}
declare module 'gatsby/dist/utils/babel-parse-to-ast.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-parse-to-ast'>;
}
declare module 'gatsby/dist/utils/browserslist.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/browserslist'>;
}
declare module 'gatsby/dist/utils/cache.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/cache'>;
}
declare module 'gatsby/dist/utils/checkpoints-promise.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/checkpoints-promise'>;
}
declare module 'gatsby/dist/utils/create-content-digest.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/create-content-digest'>;
}
declare module 'gatsby/dist/utils/create-node-id.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/create-node-id'>;
}
declare module 'gatsby/dist/utils/eslint-config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/eslint-config'>;
}
declare module 'gatsby/dist/utils/get-hash-fn.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-hash-fn'>;
}
declare module 'gatsby/dist/utils/get-ssl-cert.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-ssl-cert'>;
}
declare module 'gatsby/dist/utils/get-static-dir.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-static-dir'>;
}
declare module 'gatsby/dist/utils/html-renderer-queue.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/html-renderer-queue'>;
}
declare module 'gatsby/dist/utils/is-32-bit-integer.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/is-32-bit-integer'>;
}
declare module 'gatsby/dist/utils/js-chunk-names.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/js-chunk-names'>;
}
declare module 'gatsby/dist/utils/local-eslint-config-finder.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/local-eslint-config-finder'>;
}
declare module 'gatsby/dist/utils/merge-gatsby-config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/merge-gatsby-config'>;
}
declare module 'gatsby/dist/utils/path.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/path'>;
}
declare module 'gatsby/dist/utils/prepare-regex.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/prepare-regex'>;
}
declare module 'gatsby/dist/utils/profile.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/profile'>;
}
declare module 'gatsby/dist/utils/source-nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/source-nodes'>;
}
declare module 'gatsby/dist/utils/test-require-error.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/test-require-error'>;
}
declare module 'gatsby/dist/utils/tracer/index.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer/index'>;
}
declare module 'gatsby/dist/utils/tracer/zipkin-local.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer/zipkin-local'>;
}
declare module 'gatsby/dist/utils/webpack-helpers.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-helpers'>;
}
declare module 'gatsby/dist/utils/webpack-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-plugins'>;
}
declare module 'gatsby/dist/utils/webpack-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-utils'>;
}
declare module 'gatsby/dist/utils/webpack.config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack.config'>;
}
declare module 'gatsby/dist/utils/websocket-manager.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/websocket-manager'>;
}
declare module 'gatsby/dist/utils/worker.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/worker'>;
}
declare module 'gatsby/graphql.js' {
  declare module.exports: $Exports<'gatsby/graphql'>;
}
