// flow-typed signature: 8d0ad07f1277e60b7b2259111fd5c052
// flow-typed version: <<STUB>>/react-emotion_v^10.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-emotion/index' {
  declare module.exports: $Exports<'react-emotion'>;
}
declare module 'react-emotion/index.js' {
  declare module.exports: $Exports<'react-emotion'>;
}
