// flow-typed signature: a327978b724c1c8af4740c83e6648922
// flow-typed version: <<STUB>>/regenerator-runtime_v^0.13.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'regenerator-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'regenerator-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'regenerator-runtime/path' {
  declare module.exports: any;
}

declare module 'regenerator-runtime/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'regenerator-runtime/path.js' {
  declare module.exports: $Exports<'regenerator-runtime/path'>;
}
declare module 'regenerator-runtime/runtime.js' {
  declare module.exports: $Exports<'regenerator-runtime/runtime'>;
}
